import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { FooterSection } from '@/app/sections/Footer'
import Landing from '@/app/sections/Landing'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-display',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-foreground selection:text-contrast`}
    >
    <div className="container mx-auto mt-24 overscroll-x-none">

      {children}
    <FooterSection></FooterSection>
    </div>
    </body>
    </html>
  )
}
