export const COLORS: Record<string, string> = {
  PYTHON: "bg-[#3873A3] text-white",
  NEXT: "bg-black text-white dark:bg-white dark:text-black",
  TAILWIND: "bg-slate-900 text-[#38BDF9] dark:bg-[#38BDF9]/60 dark:text-white",
  EXPO: "bg-black text-white dark:bg-white dark:text-black",
  MACHINE_VISION: "bg-white text-black",
  MERLIC: "bg-white text-black",
  REACT_NATIVE: "bg-[#61DAFB] text-black",
  TYPESCRIPT: "bg-[#3078C6] text-white",
  REACT: "bg-[#61DAFB] text-black",
  JAVASCRIPT: "bg-[#EFD81A] text-black",
  NODE_JS: "bg-[#417E37] text-white",
  RSTUDIO: "bg-[#2165B7] text-white",
  ARDUINO: "bg-[#009296] text-white",
  MQTT: "bg-[#5C0468] text-white",
  IFTTT: "bg-black text-white dark:bg-white dark:text-black",
  GRAFANA: "bg-gradient-to-r from-[#CD503E] to-[#EFB923] text-white ",
  MYSQL: "bg-[#035D85] text-white",
};